### ISSUE TITLE
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()

### ISSUE THREAD

**Issue by gasilva** [pablormier/yabox#39]
I got this error when executing an minimization operation with yabox.
Usually this is caused by boolean or logical operation. Pandas is a suspect.

```
Traceback (most recent call last):
  File "/home/ats4i/Desktop/corona/dataAndModelsCovid19/adjustInitalConditionsS0DateI0WcasesWrecYabox.py", line 157, in <module>
    optimal.append(opt(country,e0,a0,r0,d0,date,version))  
  File "/home/ats4i/Desktop/corona/dataAndModelsCovid19/adjustInitalConditionsS0DateI0WcasesWrecYabox.py", line 57, in opt
    for step in de.geniterator():
  File "/home/ats4i/anaconda3/lib/python3.7/site-packages/yabox/algorithms/de.py", line 170, in geniterator
    it = self.iterator()
  File "/home/ats4i/anaconda3/lib/python3.7/site-packages/yabox/algorithms/de.py", line 167, in iterator
    return iter(DEIterator(self))
  File "/home/ats4i/anaconda3/lib/python3.7/site-packages/yabox/algorithms/de.py", line 10, in __init__
    self.best_fitness = np.minimum(self.fitness)
  File "/home/ats4i/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1555, in __nonzero__
    self.__class__.__name__
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by gasilva** [comment]
I was using pandas...now the error is gone.
